### ISSUE TITLE
source compile error

### ISSUE THREAD

**Issue by uwegeercken** [kuzudb/kuzu#1437]
I have pulled the latest sources and tried to to compile:

```
make clean-all && make all NUM_THREADS=6
```
I get following errors:
```
/home/uwe/development/git/kuzu/src/include/storage/buffer_manager/buffer_manager.h:160:20: Fehler: »function« in Namensraum »std« bezeichnet keinen Templatetyp
  160 |         const std::function<void(uint8_t*)>& func);
      |                    ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/storage/buffer_manager/buffer_manager.h:7:1: Anmerkung: »std::function« ist im Header »<functional>« definiert; haben Sie vergessen, »#include <functional>« zu schreiben?
    6 | #include "storage/buffer_manager/bm_file_handle.h"
  +++ |+#include <functional>
    7 | 
/home/uwe/development/git/kuzu/src/include/storage/buffer_manager/buffer_manager.h:160:28: Fehler: expected »,« or »...« before »<« token
  160 |         const std::function<void(uint8_t*)>& func);
      |                            ^
gmake[3]: *** [src/common/CMakeFiles/kuzu_common.dir/build.make:132: src/common/CMakeFiles/kuzu_common.dir/in_mem_overflow_buffer_utils.cpp.o] Fehler 1
gmake[3]: Verzeichnis „/home/uwe/development/git/kuzu/build/release“ wird verlassen
[ 38%] Built target kuzu_common_arrow
gmake[3]: Verzeichnis „/home/uwe/development/git/kuzu/build/release“ wird verlassen
gmake[2]: *** [CMakeFiles/Makefile2:2685: src/common/CMakeFiles/kuzu_common.dir/all] Fehler 2
gmake[2]: Verzeichnis „/home/uwe/development/git/kuzu/build/release“ wird verlassen
gmake[1]: *** [Makefile:136: all] Fehler 2
gmake[1]: Verzeichnis „/home/uwe/development/git/kuzu/build/release“ wird verlassen
make: *** [Makefile:48: all] Fehler 2

```

I am using Fedora Workstation 37 and gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4 and cmake version 3.26.1

**Comment by mewim** [comment]
Hi @uwegeercken we can reproduce this locally with Fedora 37. We are working on fixing this.

**Comment by ray6080** [comment]
Hi @uwegeercken , this should be fixed in #1458 , could you help us verify if things are fine now on your side?

**Comment by uwegeercken** [comment]
I just pulled the latest status from the master branch. I still get errors:

```
In Datei, eingebunden von /home/uwe/development/git/kuzu/src/include/common/types/date_t.h:3,
                 von /home/uwe/development/git/kuzu/src/include/common/types/types_include.h:3,
                 von /home/uwe/development/git/kuzu/src/include/common/type_utils.h:6,
                 von /home/uwe/development/git/kuzu/src/include/common/types/value.h:5,
                 von /home/uwe/development/git/kuzu/src/include/binder/expression/parameter_expression.h:3,
                 von /home/uwe/development/git/kuzu/src/binder/bind_expression/bind_parameter_expression.cpp:1:
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:13:15: Warnung: ausführliche Typ-Spezifikation für einen enum mit Gültigkeitsbereich darf nicht das Schlüsselwort »class« verwenden
   13 | KUZU_API enum class DatePartSpecifier : uint8_t {
      |          ~~~~ ^~~~~
      |               -----
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:13:39: Fehler: »:« in Spezifikation mit geschachteltem Namen gefunden, »::« erwartet
   13 | KUZU_API enum class DatePartSpecifier : uint8_t {
      |                                       ^
      |                                       ::
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:13:21: Fehler: »DatePartSpecifier« wurde nicht deklariert
   13 | KUZU_API enum class DatePartSpecifier : uint8_t {
      |                     ^~~~~~~~~~~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:13:49: Fehler: expected unqualified-id before »{« token
   13 | KUZU_API enum class DatePartSpecifier : uint8_t {
      |                                                 ^
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:51:32: Fehler: »uint64_t« bezeichnet keinen Typ
   51 |     interval_t operator/(const uint64_t& rhs) const;
      |                                ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:1:1: Anmerkung: »uint64_t« ist im Header »<cstdint>« definiert; haben Sie vergessen, »#include <cstdint>« zu schreiben?
  +++ |+#include <cstdint>
    1 | #pragma once
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:82:55: Fehler: »uint64_t« wurde nicht deklariert
   82 |     KUZU_API static void addition(interval_t& result, uint64_t number, std::string specifierStr);
      |                                                       ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:84:26: Fehler: »uint64_t« wurde nicht deklariert
   84 |         std::string buf, uint64_t& pos, uint64_t len, interval_t& result);
      |                          ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:84:41: Fehler: »uint64_t« wurde nicht deklariert
   84 |         std::string buf, uint64_t& pos, uint64_t len, interval_t& result);
      |                                         ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:85:61: Fehler: »uint64_t« wurde nicht deklariert
   85 |     KUZU_API static interval_t FromCString(const char* str, uint64_t len);
      |                                                             ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:91:34: Fehler: »DatePartSpecifier« wurde nicht deklariert
   91 |         std::string specifier_p, DatePartSpecifier& result);
      |                                  ^~~~~~~~~~~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/interval_t.h:92:45: Fehler: »DatePartSpecifier« wurde nicht deklariert
   92 |     KUZU_API static int32_t getIntervalPart(DatePartSpecifier specifier, interval_t& timestamp);
      |                                             ^~~~~~~~~~~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/date_t.h:71:57: Fehler: »uint64_t« wurde nicht deklariert
   71 |     KUZU_API static date_t FromCString(const char* str, uint64_t len);
      |                                                         ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/date_t.h:76:26: Fehler: »uint64_t« wurde nicht deklariert
   76 |         const char* buf, uint64_t len, uint64_t& pos, date_t& result);
      |                          ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/date_t.h:76:40: Fehler: »uint64_t« wurde nicht deklariert
   76 |         const char* buf, uint64_t len, uint64_t& pos, date_t& result);
      |                                        ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/date_t.h:92:26: Fehler: »uint64_t« wurde nicht deklariert
   92 |         const char* buf, uint64_t len, uint64_t& pos, int32_t& result);
      |                          ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/date_t.h:92:40: Fehler: »uint64_t« wurde nicht deklariert
   92 |         const char* buf, uint64_t len, uint64_t& pos, int32_t& result);
      |                                        ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/date_t.h:102:41: Fehler: »DatePartSpecifier« wurde nicht deklariert
  102 |     KUZU_API static int32_t getDatePart(DatePartSpecifier specifier, date_t& date);
      |                                         ^~~~~~~~~~~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/date_t.h:104:34: Fehler: »DatePartSpecifier« wurde nicht deklariert
  104 |     KUZU_API static date_t trunc(DatePartSpecifier specifier, date_t& date);
      |                                  ^~~~~~~~~~~~~~~~~
In Datei, eingebunden von /home/uwe/development/git/kuzu/src/include/common/types/types_include.h:4:
/home/uwe/development/git/kuzu/src/include/common/types/dtime_t.h:40:58: Fehler: »uint64_t« wurde nicht deklariert
   40 |     KUZU_API static dtime_t FromCString(const char* buf, uint64_t len);
      |                                                          ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/dtime_t.h:42:26: Fehler: »uint64_t« wurde nicht deklariert
   42 |         const char* buf, uint64_t len, uint64_t& pos, dtime_t& result);
      |                          ^~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/dtime_t.h:42:40: Fehler: »uint64_t« wurde nicht deklariert
   42 |         const char* buf, uint64_t len, uint64_t& pos, dtime_t& result);
      |                                        ^~~~~~~~
In Datei, eingebunden von /home/uwe/development/git/kuzu/src/include/common/types/types_include.h:9:
/home/uwe/development/git/kuzu/src/include/common/types/timestamp_t.h:75:46: Fehler: »DatePartSpecifier« wurde nicht deklariert
   75 |     KUZU_API static int32_t getTimestampPart(DatePartSpecifier specifier, timestamp_t& timestamp);
      |                                              ^~~~~~~~~~~~~~~~~
/home/uwe/development/git/kuzu/src/include/common/types/timestamp_t.h:77:39: Fehler: »DatePartSpecifier« wurde nicht deklariert
   77 |     KUZU_API static timestamp_t trunc(DatePartSpecifier specifier, timestamp_t& date);
      |                                       ^~~~~~~~~~~~~~~~~
gmake[3]: *** [src/binder/bind_expression/CMakeFiles/kuzu_binder_bind_expression.dir/build.make:160: src/binder/bind_expression/CMakeFiles/kuzu_binder_bind_expression.dir/bind_parameter_expression.cpp.o] Fehler 1
gmake[2]: *** [CMakeFiles/Makefile2:2581: src/binder/bind_expression/CMakeFiles/kuzu_binder_bind_expression.dir/all] Fehler 2

```

**Comment by ray6080** [comment]
Hi @uwegeercken , thanks for the detailed error log! It looks like I was using a different version of gcc compiler (v12.x) with yours (v13.x), though with the same version of fedora and cmake. Let me try to reproduce your errors on my side, and then get back to you.

**Comment by ray6080** [comment]
Hi @uwegeercken , I've reproduced the error inside docker, and merged a pr #1467 into master for fix. Can you double check if this can fix your problems?
