### ISSUE TITLE
Bug: GDS recursive join consumes too much memory

### ISSUE THREAD

**Issue by ted-wq-x** [kuzudb/kuzu#4459]
### Kùzu version

master

### What operating system are you using?

CentOS Linux release 8.5.2111

### What happened?

Query like “match p=(a:person {id:24189255912498})-[f*2]-(b) return p limit 20” in ldbc sf100,150GB memory is quickly exhausted.

**Comment by andyfengHKU** [comment]
Hi @ted-wq-x, this should be resolved in #4471

**Comment by ted-wq-x** [comment]
I tested it on the lasted master branch and the problem still exists.Revision number 21dbaeac4d8a94821c3090be4ab1c8df5799cf48

**Comment by andyfengHKU** [comment]
Hi @ted-wq-x 

Can u pull the latest master and run the following
```
match p=(a:person {id:24189255912498})-[f*2]-(b) 
hint (a JOIN f) JOIN b
return p limit 20
```

**Comment by ted-wq-x** [comment]
Memory peak 5.7g,time consuming 4.1s.

**Comment by ray6080** [comment]
This is solved now.
