### ISSUE TITLE
Bug: LSQB Q3 Performance

### ISSUE THREAD

**Issue by adsharma** [kuzudb/kuzu#4967]
### Kùzu version

v0.8.2

### What operating system are you using?

Ubuntu 24.04

### What happened?

Ran LSQB with SF=0.3 and 16 Threads.

There was a noticeable performance delta between duckdb 1.2.0 and kuzu 0.8.2
duckdb: 0.034s
kuzudb: 78.8s

Is this known?

**Comment by adsharma** [comment]
I'm guessing that this is known to you already. Last successful benchmark run [here](https://github.com/kuzudb/kuzu/actions/runs/13147197567) had a timeout for Q3.

I see similar slow results for Q9 (2-5x slower than duckdb). You had a timeout for that query as well on the CI benchmark run.

**Comment by andyfengHKU** [comment]
Hi @adsharma,

yes we are aware of this #4843 is to mitigate this problem. Though the bigger problem is the the cardinality estimator is still not smart enough. We are still working on this. Happy to know on which we are slower than DuckDB! And we will fix them

**Comment by adsharma** [comment]
Thank you! I'll retest and close after the next release.

**Comment by adsharma** [comment]
Verified that the regression is fixed:

```
KuzuDB-0.9.0    16 threads      0.1     2       0.0352  82990
KuzuDB-0.9.0    16 threads      0.1     3       3.8331  30456
KuzuDB-0.9.0    16 threads      0.1     4       0.0357  784511
KuzuDB-0.9.0    16 threads      0.1     5       0.0340  1079722
KuzuDB-0.9.0    16 threads      0.1     6       0.1563  55607896
KuzuDB-0.9.0    16 threads      0.1     7       0.0446  1628132
KuzuDB-0.9.0    16 threads      0.1     8       0.1363  537142
KuzuDB-0.9.0    16 threads      0.1     9       0.4405  51009398
```

**Comment by andyfengHKU** [comment]
Cool. The performance still doesn't look great. I would open a new issue and continue improve LSQB and LDBC
